export const ORDER_STATES = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  CONFIRMED: "CONFIRMED",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  REFUND_INITIATED: "REFUND_INITIATED",
  REFUNDED: "REFUNDED"
};

export const ORDER_TRANSITIONS = {
  [ORDER_STATES.PENDING_PAYMENT]: [
    ORDER_STATES.CONFIRMED,
    ORDER_STATES.CANCELLED
  ],
  [ORDER_STATES.CONFIRMED]: [
    ORDER_STATES.SHIPPED,
    ORDER_STATES.CANCELLED
  ],
  [ORDER_STATES.SHIPPED]: [ORDER_STATES.DELIVERED],
  [ORDER_STATES.DELIVERED]: [ORDER_STATES.REFUND_INITIATED],
  [ORDER_STATES.REFUND_INITIATED]: [ORDER_STATES.REFUNDED],
  [ORDER_STATES.REFUNDED]: [],
  [ORDER_STATES.CANCELLED]: []
};

export const canTransition = (from, to) => {
  return ORDER_TRANSITIONS[from]?.includes(to) || false;
};
